      Double Precision CX2, C1PX, C1MX, CLX, CLX2, CL1PX, CL1MX, CL1MX2, CS3X,
     &                 CPFGMX, CPFGX, CPFFMX, CPFFX, CPGFX, CPGFMX, 
     &                 CS1X, CS2X, CPGG, CMPGG, AAA, BBB, CCC, DDD, 
     &                 PQQ, PQQB

c     need values   
      Double Precision C20S3, C2S3, C4S3, CPI2S3, C16S9, C11S6, C4S9, C5S3,
     &                 CPIA, C10S9, C112S9, C16S3, C14S3, C40S3, C40S9, 
     &                 C136S3, C14S9, C182S9, C38S3, C44S3, C35S18, C44S9, 
     &                 C62S9, C8S3, C28S3, C52S3,
     &                 CPIB, CPIC, CPIE, CPIF, PI
      Common/QCDnum_Const/C20S3, C2S3, C4S3, CPI2S3, C16S9, C11S6, C4S9, C5S3,
     &                 CPIA, C10S9, C112S9, C16S3, C14S3, C40S3, C40S9, 
     &                 C136S3, C14S9, C182S9, C38S3, C44S3, C35S18, C44S9, 
     &                 C62S9, C8S3, C28S3, C52S3,
     &                 CPIB, CPIC, CPIE, CPIF, PI
      Double Precision DMB_DILOG
      
